<%

' DK, Apr 01, 2008 - version 1.0

With gLangDict

	.Item("lang") = "en-ca"
	.Item("lang_switch") = "Français"

	.Item("L_ALL_MARKETS_REIT") = "All Markets (REIT)"
	.Item("L_VANCOUVER") = "Vancouver"
	.Item("L_EDMONTON") = "Edmonton"
	.Item("L_CALGARY") = "Calgary"
	.Item("L_TORONTO") = "Toronto"
	.Item("L_OTTAWA") = "Ottawa"
	.Item("L_MONTREAL") = "Montreal"
	.Item("L_QUEBEC_CITY") = "Quebec City"
	.Item("L_FREDERICTON") = "Fredericton"
	.Item("L_MONCTON") = "Moncton"
	.Item("L_CHARLOTTETOWN") = "Charlottetown"
	.Item("L_HALIFAX") = "Halifax"
	.Item("L_ST_JOHNS") = "St. John's"
	.Item("L_SAINT_JOHN") = "Saint John"
	.Item("L_BC") = "Tier II Regional Mall only: BC"
	.Item("L_ALBERTA") = "Tier II Regional Mall only: Alberta"
	.Item("L_SASKATCHEWAN") = "Tier II Regional Mall only: Saskatchewan"
	.Item("L_MANITOBA") = "Tier II Regional Mall only: Manitoba"
	.Item("L_ONTARIO") = "Tier II Regional Mall only: Ontario"
	.Item("L_QUEBEC") = "Tier II Regional Mall only: Quebec"
	.Item("L_ATLANTIC") = "Tier II Regional Mall only: Atlantic"

	.Item("L_N/A") = "N/A"
	.Item("L_OFFICE") = "Office"
	.Item("L_RETAIL") = "Retail"
	.Item("L_INDUSTRIAL") = "Industrial"
	.Item("L_MULTI_RES") = "Multi-Res"

	.Item("L_REIT_UNITS") = "REIT Units"
	.Item("L_DOWNTOWN_OFFICE_LAND") = "Downtown Office Land"
	.Item("L_SUBURBAN_OFFICE_LAND") = "Suburban Office Land"
	.Item("L_DOWNTOWN_CLASS_AA_OFFICE") = "Downtown Class ""AA"" Office"
	.Item("L_DOWNTOWN_CLASS_AA_OFFICE_LEASEHOLD") = "Downtown Class ""AA"" Office Leasehold"
	.Item("L_DOWNTOWN_CLASS_B_OFFICE") = "Downtown Class ""B"" Office"
	.Item("L_SUBURBAN_CLASS_A_OFFICE") = "Suburban Class ""A"" Office"
	.Item("L_SUBURBAN_CLASS_B_OFFICE") = "Suburban Class ""B"" Office"
	.Item("L_TIER_I_REGIONAL_MALL") = "Tier I Regional Mall"
	.Item("L_TIER_II_REGIONAL_MALL") = "Tier II Regional Mall"
	.Item("L_FOOD_ANCHORED_RETAIL_STRIP") = "Food Anchored Retail Strip"
	.Item("L_POWER_CENTRE") = "Power Centre"
	.Item("L_COMMUNITY_MALL") = "Enclosed Community Mall"
	.Item("L_MULTI_TENANT_INDUSTRIAL") = "Multi-Tenant Industrial"
	.Item("L_SINGLE_TENANT_INDUSTRIAL") = "Single Tenant Industrial"
	.Item("L_INDUSTRIAL_LAND") = "Industrial Land"
	.Item("L_SUBURBAN_MULTI_UNIT_RESIDENTIAL") = "Suburban Multiple Unit Residential"  ' used to be Multi-Unit Residential
	.Item("L_DOWNTOWN_MULTI_UNIT_RESIDENTIAL") = "Downtown Multiple Unit Residential"  ' new one added on Nov 20, 2008
	.Item("L_HOTEL") = "Hotel"
	.Item("L_MIDTOWN_CLASS_A") = "Montreal Midtown Class A Office"
	.Item("L_MONTREAL_SUBURBAN_MULTI_UNIT_RESIDENTIAL") = "Montreal Midtown Multiple Unit Residential"  ' used to be Montreal Suburban Multiple Unit Residential
	.Item("L_SINGLE_TENANT") = "Single Tenant Retail"
	.Item("L_CLASS_A_OFFICE") = "Class ""A"" Office"
	.Item("L_CLASS_B_OFFICE") = "Class ""B"" Office"

	.Item("L_VERY_POOR") = "Very Poor"
	.Item("L_POOR") = "Poor"
	.Item("L_GOOD") = "Good"
	.Item("L_VERY_GOOD") = "Very Good"
	.Item("L_EXCELLENT") = "Excellent"

	.Item("L_INCREASE") = "Increase"
	.Item("L_DECREASE") = "Decrease"
	.Item("L_NO_CHANGE") = "No Change"

	.Item("L_MONTHLY") = "Monthly"
	.Item("L_ANNUALLY") = "Annually"
	.Item("L_DONTKNOW") = "Don't know"

	.Item("L_YES") = "Yes"
	.Item("L_NO") = "No"
	.Item("L_SOMETIMES") = "Sometimes"

	.Item("L_NOIMPACT") = "No Impact"
	.Item("L_INCREASE_25") = "Increase - 25 BPS"
	.Item("L_INCREASE_50") = "Increase - 50 BPS"
	.Item("L_INCREASE_75") = "Increase - 75 BPS"
	.Item("L_INCREASE_100") = "Increase - 100 BPS"
	.Item("L_INCREASE_100PLUS") = "Increase - More than 100 BPS"

	.Item("L_UNKNOWN") = "Unknown"
	.Item("L_OWNERSHIP_SIDE_OF_PENSION_FUNDS_PENSION_FUND_ADVISORS") = "Ownership side of pension funds/Pension fund advisors"
	.Item("L_PUBLICLY_TRADED_CORPORATIONS_REITS") = "Publicly traded corporations REITs"
	.Item("L_OWNERSHIP_SIDE_OF_BANKS_LIFE_COMPANIES") = "Ownership side of Banks/Life companies"
	.Item("L_PRIVATE_COMPANIES_DOMESTIC") = "Private Companies - Domestic"
	.Item("L_PRIVATE_COMPANIES_FOREIGN") = "Private Companies - Foreign"
	.Item("L_INVESTMENT_BANKS_REAL_ESTATE_BROKERS_REAL_ESTATE_ANALYSTS") = "Investment Banks/Real Estate Brokers/Real Estate Analysts"
	.Item("L_LENDING_SIDE_OF_BANKS_LIFE_COMPANIES_PENSION_FUNDS") = "Lending side of banks/Life companies/Pension funds"
	.Item("L_OTHER") = "Other"

	.Item("L_LT5") = "LESS THAN 5"
	.Item("L_5_10") = "5 - 10"
	.Item("L_10_20") = "10 - 20"
	.Item("L_20_50") = "20 - 50"
	.Item("L_50_100") = "50 - 100"
	.Item("L_GT100") = "MORE THAN 100"

	.Item("L_BANK_OF_MONTREAL") = "Bank of Montreal"
	.Item("L_BANK_OF_NOVA_SCOTIA") = "Bank of Nova Scotia"
	.Item("L_CIBC") = "CIBC"
	.Item("L_GWL") = "GWL"
	.Item("L_GE_CAPITAL") = "G.E. Capital"
	.Item("L_GMAC") = "GMAC"
	.Item("L_MANULIFE") = "Manulife"
	.Item("L_MASS_MUTUAL") = "Mass Mutual"
	.Item("L_METROPOLITAN_LIFE") = "Metropolitan Life"
	.Item("L_MERRILL_LYNCH") = "Merrill Lynch"
	.Item("L_SUN_LIFE") = "Sun Life"
	.Item("L_OMERS") = "OMERS"
	.Item("L_ROYAL_BANK") = "Royal Bank"
	.Item("L_STANDARD_LIFE") = "Standard Life"
	.Item("L_TIAA_CREF") = "TIAA - CREF"
	.Item("L_TORONTO_DOMINION_BANK_CMO") = "Toronto Dominion Bank / CMO"
	.Item("L_CAISSE_DE_DEPOT_CDPQ_MCAP") = "Caisse de Depot / CDPQ / MCAP"
	.Item("L_OTHERS") = "Others"

	.Item("title_default") = "Altus InSite Investment Trends Survey Results"
	.Item("title_about") = "About Altus InSite Investment Trends Survey"
	.Item("title_password_retrieval") = "Password Retrieval"
	.Item("title_outlook_2008_1") = "Outlook for Quarter 1 2008"
	.Item("title_outlook_2008_2") = "Outlook for Quarter 2 2008"
	.Item("title_outlook_2008_3") = "Outlook for Quarter 3 2008"
	.Item("title_outlook_2008_4") = "Outlook for Quarter 4 2008"
	.Item("title_outlook_2009_1") = "Outlook for Quarter 1 2009"
	.Item("title_outlook_2009_2") = "Outlook for Quarter 2 2009"
	.Item("title_outlook_2009_3") = "Outlook for Quarter 3 2009"
	.Item("title_outlook_2009_4") = "Outlook for Quarter 4 2009"
	.Item("title_superuser") = "Super-User Functions"

	.Item("head_default") = "Investment Trends Survey"
	.Item("head_user_name") = "Market Perspective Provided by:"
	.Item("head_user_email") = "e-mail:"
	.Item("head_user_phone") = "Tel:"
	.Item("head_user_datetime") = "Report Generated:"

	.Item("foot_copyright") = "Altus InSite &copy; Altus Group Limited 1999-2008"

	.Item("menu_logout") = "Log out"
	.Item("menu_loggedin") = "Logged In"
	.Item("menu_myaccount") = "My Account"

	.Item("menu_home") = "Home"
	.Item("menu_search") = "Search"
	.Item("menu_office") = "Office"
	.Item("menu_industrial") = "Industrial"
	.Item("menu_retail") = "Retail"
	.Item("menu_ITS") = "Investment Trends Survey"
	.Item("menu_reports") = "My Reports"
	.Item("menu_availablespacesurveys") = "Available Space Surveys"
	.Item("menu_marketactivity") = "Market Activity"
	.Item("menu_marketingdynamics") = "Marketing Dynamics"
	.Item("menu_manageportfolio") = "Manage Your Portfolio"
	.Item("menu_freetools") = "Free Tools"
	.Item("menu_addlisting") = "Add a Listing"
	.Item("menu_updateproperties") = "Update Properties"
	.Item("menu_tenantresourcecentre") = "Tenant Resource Centre"
	.Item("menu_researchreports") = "Research Report"
	.Item("menu_submittransactions") = "Submit Transactions"
	.Item("menu_about") = "About Altus InSite"
	.Item("menu_whatwedo") = "What We Do"
	.Item("menu_officedefinitions") = "Office Definitions"
	.Item("menu_officegeography") = "Office Geography"
	.Item("menu_industrialdefinitions") = "Industrial Definitions"
	.Item("menu_benchmarkproperties") = "Benchmark Properties"
	.Item("menu_researchmethodology") = "Research Methodology"
	.Item("menu_barometerdefinitions") = "Barometer Definitions"
	.Item("menu_retaildefinitions") = "Retail Definitions"
	.Item("menu_copyright") = "Copyright Details"
	.Item("menu_subscription") = "Subscription Options"
	.Item("menu_contact") = "Contact"

	.Item("menu_currentqtrtoc") = "List of Available<br>Graphs for "
	.Item("menu_currentqtrxls") = "Non charted data (MS Excel file) for "
	.Item("menu_additional_a") = "Inventory, New Supply and Forecasting Tool"
	.Item("menu_additional_b") = "Malls, Stores and Retailers"
	.Item("menu_additional_c") = "Inventory and Available Properties"
	.Item("menu_additional_d") = "Current Survey Results"
	.Item("menu_findmore_a") = "Contact Us"
	.Item("menu_findmore_b") = "ITS Definitions"
	.Item("menu_findmore_c") = "Research Methodology"
	.Item("menu_findmore_d") = "Copyright"
	.Item("menu_findmore_e") = "Overwiew"
	.Item("menu_historicalqtr") = "Change View to Historical<br>Quarter Snapshot" ' used to be "Display Historical Quarter Snapshot"
	.Item("menu_qtrfrequency") = "Quarterly Frequency<br>of All Graphs"
	.Item("menu_currentqtr") = "Search Current<br>Quarter Results"
	.Item("menu_superuser") = "ITS Super-User Functions"
	.Item("menu_space4lease") = "Click here to learn more"

	.Item("menu_label_producedby") = "Produced by:"
	.Item("menu_label_additional") = "Additional Data and Perspective"
	.Item("menu_label_findmore") = "Find Out More"

	.Item("results") = "Results"
	.Item("welcome") = "Welcome"
	.Item("next") = "Next"
	.Item("back") = "Back"
	.Item("select") = "Select"
	.Item("login") = "Login"
	.Item("login2") = "Guest Access"
	.Item("check") = "Check"
	.Item("password_retrieval") = "Password Retrieval"

	.Item("userid") = "User ID"
	.Item("password") = "Password"

	.Item("standard") = "Standard"
	.Item("special") = "Special"

	.Item("image_hires_jpg") = "300dpi JPEG image"
	.Item("image_hires_png") = "300dpi PNG image"

	.Item("report_label") = "REPORT TYPE"
	.Item("product_label") = "PRODUCT TYPE"
	.Item("property_label") = "PROPERTY"
	.Item("market_label") = "MARKET"

	.Item("email_label") = "Email address:"

	.Item("all") = "All"
	.Item("all_products") = "All Products"
	.Item("all_atlantic") = "All Atlantic"
	.Item("all_national") = "All National"
	.Item("all_markets") = "All Markets"
	.Item("all_available") = "All Available Products"
	.Item("all_available_office") = "All Available Office Products"
	.Item("all_available_retail") = "All Available Retail Products"
	.Item("all_available_industrial") = "All Available Industrial Products"

	.Item("link_login") = "Click here to login"

	.Item("intro_0_0") = "Welcome to the Investment Trends Survey results for the current quarter. We are pleased that a large proportion of the Canadian real estate community are not only contributors to the survey, but also subscribers. The objective of the survey is to study the perceptions of key decision makers within the commercial real estate industry and to interpret the trends that will impact future markets. It is important to emphasize, however, that caution is required with respect to the interpretation of valuation parameters set out herein. In the rapidly changing investment market, survey results can lag actual transaction details and indicate lower/higher valuation parameters.<br><br>The questionnaire was distributed earlier this quarter to professionals within the commercial real estate investment community in Canada and the broad range of respondents is considered by our statistician to be an accurate representation of the commercial real estate market."
	.Item("intro_0_1") = "The survey provides a valuable insight into the trends in the Canadian commercial property market, which has been repositioning, following a 6 year upbeat bull market, which peaked in Spring 2007. During the last nine months, the <em>Investment Trends Survey</em> results have reflected a range of attitudes from caution and uncertainty to hints of confidence, as the market grappled with the impact of the deepening crisis in the United States and its impact on global financial markets. Unlike the financial markets, changes in real estate tend to be more subtle and the market players do not move in unison. As more information becomes available, participants have greater opportunity to weigh risk and respond, but the market remains imperfect. What is clear is that despite signs of growing economic weakness in Eastern Canada and sustained gloom from the United States, that the Canadian market is demonstrating surprising resilience and sustained demand for top quality assets. At the other end of the buyer scale, the appetite for secondary assets and markets has weakened, in lockstep with a more challenging debt environment. <a href=""../static/default.asp?action=2008_Q1"">More...</a>"
	'.Item("intro_0_2") = "Welcome to the 2nd Quarter 2008 Investment Trends Survey results. In this, our tenth year of administering the surveys and distributing the results, we are pleased that a large proportion of the Canadian real estate community are not only contributors but also subscribers. The objective of the survey is to study the perceptions of key decision makers within the commercial real estate industry and to interpret the trends that will impact future markets. It is important to emphasize, however, that caution is required with respect to the interpretation of valuation parameters set out herein. In today's rapidly changing investment market, survey results can lag actual transaction details and indicate lower/higher valuation parameters.<br><br>The Q2 2008 questionnaire was distributed earlier this quarter to professionals within the commercial real estate investment community in Canada. The survey was completed by 124 respondents and, this broad range of respondents is considered by our statistician to be an accurate representation of the commercial real estate market."
	.Item("intro_0_2") = "The Q2 2008 survey provides confirmation that the Canadian commercial property market, has finally, after 12 months of hesitancy, responded to the growing US and worldwide economic crisis. Finally, based on ITS responses, the Canadian commercial property bull market, which sustained for six years, is over. During the last three quarters, the ITS results demonstrated remarkable resilience, reflected in a range of attitudes from caution and uncertainty to hints of confidence. However, the Q2 2008 barometer readings and valuation parameters at last reflect a ""sea change"" in attitude. While sentiment is still slightly bullish, demand has weakened across the country and yield requirements have stiffened for all asset types. The market has fully re-priced itself to reflect risk and quality. In some markets, given weakening demand and lending constraints, some lower quality assets may be close to being illiquid. At the other end of the scale, prime assets are still in demand, but are attracting higher yield parameters and smaller pools of buyers. The seller’s side is characterized by a state of inertia - a time to sit tight and a reluctance to sell under current conditions. <a href=""../static/default.asp?action=2008_Q2"">More...</a>"
	'.Item("intro_0_3") = "There is definitely a chill in the air of commercial real estate markets across Canada, although a reasonable stability of prices and yields in the major investment types remains. The chill is offset by a persistent and still greater proportion of bulls compared to bears. The respondents to the Altus survey were questioned in August 2008 prior to the financial markets turmoil at the time of this writing in mid September. Nonetheless our overriding sense from more recent chatter is that very few are wringing their hands and many still see this as a more stable opportunity to participate in Canadian real estate. <a href=""../static/default.asp?action=2008_Q3"">More...</a>"
	.Item("intro_0_3") = "Given the year-long, global financial market turmoil there is definitely a chill in the air of commercial real estate markets across Canada although investment sentiment reflects relative stability of prices and yields for Class A office, retail, industrial and multi-family assets. Our Q3 2008 Survey results still point to a higher proportion of investors who are bullish compared to those who are bearish, <em><strong>however it is important to note that the 110 respondents to the Altus survey were questioned in August 2008 prior to the carnage taking place at the time of this writing early October</strong></em>. <a href=""../static/default.asp?action=2008_Q3"">More...</a>"
	.Item("intro_0_4") = "The world financial crisis and the economic slowdown in Canada has finally caught up with the commercial property market. The weakening investment trends previously reported in the secondary markets, have now shifted to prime assets. The Q4 Investment Trends Survey reflects a growing erosion of demand and increasing yield requirements for prime retail, industrial and office properties. For the first time in the history of ITS, the Location Barometer indicates bearish demand (more sellers than buyers) in all Canadian locations except Ottawa. The lack of available bank financing, coupled with growing economic weakness and unemployment, has dampened investor confidence in commercial real estate. In this deepening economic downturn, the only stability in prices and yields is reported for multi unit residential product. <a href=""../static/default.asp?action=2008_Q4"">More...</a>"
	.Item("intro_0_5") = "The Canadian commercial property market continues to report weakening investment trends and at this stage of the economic cycle, all categories of assets are subject to downward pressure on prices. The improvement in the flow of credit from lending institutions has not translated into improved confidence in the real estate investment market and most qualified investors appear to be adopting a “wait and see” attitude. The Q1 2009 Investment Trends Survey reports increasing yield requirements for prime retail, industrial and office properties, as both vendors and purchasers search for the bottom of the market. For the second quarter, the Location Barometer indicates bearish demand (more sellers than buyers) in all Canadian locations except Ottawa. The nation’s capital, while not immune to the struggles associated with the waning US economy, is shielded by stable public administration employment and slightly positive GDP growth. Momentum indicators are extremely weak, with shallow demand (few buyers) and shallow supply (few sellers). In Ottawa the location barometer indicated one buyer for every seller and in Calgary, at number seven position, the barometer indicates there are 1.9 sellers for every buyer. Eastern cities of Toronto, Montreal, Quebec City and Halifax are slightly bearish but stable. Calgary and Edmonton are least favoured, in response to low energy prices, rising unemployment and unusually weak GDP projections for 2009. <a href=""../static/default.asp?action=2009_Q1"">More...</a>"
	.Item("intro_0_6") = "After an 18 month downward slide in the commercial property market, our Q2 2009 Investment Trends Survey reports weak signs of a possible return to stability. The survey results mirror the early signs of recovery demonstrated by some other sectors of the economy, such as oil prices, stock market indices and single family housing statistics. However economists warn that unemployment is deepening and manufacturing performance is still weak, resulting in a slow choppy recovery. So, can it be concluded the mild opportunism reported in this survey may be a ""false"" bottom or the first phase of a ""double dip""? The rebound in the commercial real estate sector traditionally lags a rebound in the rest of the economy. Forecasting is difficult at best and subsequent surveys will provide the answers as to whether this is the start of a rebound or a fleeting blip in a recovery cycle. <a href=""../static/default.asp?action=2009_Q2"">More...</a>"
	.Item("intro_0_7") = "The results from the Investment Trends Survey for Q3 2009 reveal growing signs of a return to stability in the Canadian commercial real estate market, tempered by caution that cash flows and values may face further erosion by a correction in rents and vacancies. Overall, the survey results reflect a more positive attitude and growing confidence in real estate investments, following a significant compression in asset values since the bull market peak in mid 2007. The Q3 2009 Survey certainly reflects stabilization in the yield requirements for prime retail, office and multi family assets, and mixed signals for industrial real estate. <a href=""../static/default.asp?action=2009_Q3"">More...</a>"
	.Item("intro_0_8") = "The results from the Investment Trends Survey for Q3 2009 reveal growing signs of a return to stability in the Canadian commercial real estate market, tempered by caution that cash flows and values may face further erosion by a correction in rents and vacancies. Overall, the survey results reflect a more positive attitude and growing confidence in real estate investments, following a significant compression in asset values since the bull market peak in mid 2007. The Q3 2009 Survey certainly reflects stabilization in the yield requirements for prime retail, office and multi family assets, and mixed signals for industrial real estate. <a href=""../static/default.asp?action=2009_Q4"">More...</a>"

	.Item("intro_1") = "Please note that all menus are contextual. After selecting a menu option, please wait for new data to load before clicking the DISPLAY REPORT button."
	.Item("intro_email") = "Enter your email address below for your information to be emailed to you:"

    .Item("info_login") = "If you are already registered, please login below using the userid and password you selected when you registered. If you have forgotten your user id or password, please click on the Password Retrieval link immediately to the right of the login button below.</p><p>If you are not registered, you can register immediately for <a href=""http://www.altusinsite.com/register.php"">Guest Acess here</a>. If you require any assistance, please <a href=""../common/cross.asp?site=main&amp;page=/contactform/index.php?KeepThis=true&amp;TB_iframe=true&amp;height=650&amp;width=590"" class=""thickbox last"">contact us</a> or <a href=""/eng/common/about.asp?action=overview"">click here for more information</a>."

	.Item("info_login2") = "Having trouble logging in?  <a href=""mailto:useradmin@altusinsite.com"">Click here</a>."
	.Item("info_login_incorrect") = "Incorrect login. You have either mistyped your information or your session has expired. Please check your User ID and Password and try again."
	.Item("info_javascript") = "It appears that JavaScript is disabled or not supported in your web browser. Although this form will function without JavaScript, for best experience it is recommended that you enable JavaScript."
	.Item("info_email_found") = "Your User ID and Password have been sent to the email address you provided."

	.Item("alt_0") = "Respondent Categories Chart"
	.Item("alt_1") = "Altus Insite"
	.Item("alt_2") = "Generate Acrobat File"

	.Item("form_a_title") = "Capital Sources and Miscellaneous Results"
	.Item("form_a_instr") = "Please select a report type from the menu below."
	.Item("form_b_title") = "Historical Perspective"
	.Item("form_b_instr") = "Please select a report type from the menu below to generate a list of available products, then select one of the available options from the Market menu."
	.Item("form_c_title") = "Current Quarter Results"
	.Item("form_c_instr") = "Please select a report type from the menu below to generate a list of available products for the current quarter, and then select one of the available options from the Market menu."

	.Item("quote_a0_0") = "A large segment of the secondary market (non-cash or leverage buyers) have been pushed to the sidelines as high debt for all but the best assets is virtually non-existent."
	.Item("quote_b0_0") = "National Real Estate Broker"
	.Item("quote_a1_0") = "The flow of capital might be tighter, but potential buyers are still lining up for quality assets"
	.Item("quote_b1_0") = "National Investment Firm"
	.Item("quote_a2_0") = "Sure, cap rates will go up, but not for trophy properties"
	.Item("quote_b2_0") = "Mortgage Lender/Lifeco"
	.Item("quote_a3_0") = "We will continue to see upward pressure on cap rates for investment grade retail, but how quickly will the upward movement happen? I don’t know!"
	.Item("quote_b3_0") = "Regional REIT"
	.Item("quote_a4_0") = "Vendor expectations remain at the low end of the cap rate range, which has inhibited some recent transactions from occurring."
	.Item("quote_b4_0") = "Multiple Unit Residential Manager"
	.Item("quote_a5_0") = "As a result of the continuing write downs due to the credit crunch, it’s a new game, which is forcing participants to go back to fundamental underwriting."
	.Item("quote_b5_0") = "National Real Estate Broker"
	.Item("quote_a6_0") = "Cap rates will stagnate and building sales will slow down dramatically within the Quebec and Montreal urban markets."
	.Item("quote_b6_0") = "National Real Estate Broker"
	.Item("quote_a7_0") = "Prestige office buildings are out; green buildings are in."
	.Item("quote_b7_0") = "National Appraisal Firm"

	.Item("quote_a0_1") = "Lenders' fears of a market crash are actually contributing to make things worse."
	.Item("quote_b0_1") = "Pension fund executive"
	.Item("quote_a1_1") = "Hopefully the recent increase in the number of available lenders will continue to push mortgage spreads toward the 200 to 220 bps area."
	.Item("quote_b1_1") = "Canadian REIT"
	.Item("quote_a2_1") = "Cap rates have definitely moved up and value down. Asset values for this year have already been adjusted downward from amounts paid during 2007."
	.Item("quote_b2_1") = "Vice President, Eastern Canada"
	.Item("quote_a3_1") = "Lending markets are not efficient at the moment as mortgage spreads, loan to value ratios, debt coverage ratios and amortization periods are all over the place."
	.Item("quote_b3_1") = "Publicly Traded Real Estate Company"
	.Item("quote_a4_1") = "With the loss of the conduit lenders borrowing is more difficult and time consuming as the remaining participants have not increased their underwriting capacity to pick up the slack."
	.Item("quote_b4_1") = "CFO, Eastern Canada"

	.Item("quote_a0_2") = "Current mortgage rate data does not address the issue of restrictive financing conditions, in other words, some lenders quote low rates but will only lend if you have three legs and 20 fingers."
	.Item("quote_b0_2") = "Senior Investment Market Analyst"
	.Item("quote_a1_2") = "Now is a time to be on the sidelines and bide my time and wait. There are cracks appearing in rental rates and risk is being priced back into decision making. There is no motivation to increase exposure to commercial real estate at this moment."
	.Item("quote_b1_2") = "Calgary private real estate investor"
	.Item("quote_a2_2") = "There is an 18-month disconnect between buyers’ expectations and sellers’ expectations: Sellers still yearn for July 2007 cap rates, while buyers are already dealing at January 2009 cap rates. By then, everyone should have adjusted to common market parameters."
	.Item("quote_b2_2") = "Senior Montreal Real Estate Executive"
	.Item("quote_a3_2") = "The flight to quality continues. High quality purchasers have cash on hand and are still looking to buy Class A product."
	.Item("quote_b3_2") = "Major Alberta Developer"
	.Item("quote_a4_2") = "A number of good quality suburban office and industrial assets have recently traded, without discount in price or lack of motivation from the strong purchasers."
	.Item("quote_b4_2") = "Major Alberta Developer"
	.Item("quote_a5_2") = "Secondary buyers do not have the same cash at hand and have obvious difficulty getting financing. For the same reasons, the pool of buyers for speculative and syndicated land has also disappeared."
	.Item("quote_b5_2") = "Major Alberta Developer"

	.Item("quote_a0_3") = "Financing is available at attractive rates but the LTV is off to a point where financing availability is classified as good only."
	.Item("quote_b0_3") = "Major Ontario Developer & Property Manager"
	.Item("quote_a1_3") = "We think there may be some interesting opportunities coming available if the pension funds ratio of equities to real estate shifts too much in favour of their real estate portfolio."
	.Item("quote_b1_3") = "Major Ontario Developer"
	.Item("quote_a2_3") = "A shot in the dark!"
	.Item("quote_b2_3") = "Major Insurance Co."
	.Item("quote_a3_3") = "It has been a good run, we have seen this before."
	.Item("quote_b3_3") = "Major Financial Institution"
	.Item("quote_a4_3") = "Overall, all assets are being re-priced at around 10% lower."
	.Item("quote_b4_3") = "Major Financial Institution"
	.Item("quote_a5_3") = "I would be curious to know who are the most likely takeover candidates among the REITs and REOCs"
	.Item("quote_b5_3") = "National Commercial Brokerage"
	.Item("quote_a6_3") = "We won't likely see any change in the state of the current real estate market before we see a stabilization of the stock market and an easing of the credit conditions."
	.Item("quote_b6_3") = "Major Financial Institution"
	.Item("quote_a7_3") = "We’re definitely in a buyers market and cap rates are on the rise. Not very optimistic!"
	.Item("quote_b7_3") = "Major Pension Fund"
	.Item("quote_a8_3") = "With the extreme scarcity of transactions, how are appraisers able to arrive at realistic values in view of the serious economic conditions?"
	.Item("quote_b8_3") = "Major BC Brokerage"
	.Item("quote_a9_3") = "With so much uncertainty, no one really knows."
	.Item("quote_b9_3") = "National Commercial Brokerage"
	.Item("quote_a10_3") = "Given the current real-estate lending market it would be very interesting to hear about what the market expectations are in this field. The content should be concerned with rate, LTV, term, amortization, recourse/no-recourse and most likely sources of funds."
	.Item("quote_b10_3") = "Major Real Estate Lender"
	.Item("quote_a11_3") = "The focus should be on availability of debt capital and understanding whether pension funds, banks, credit unions and life companies are increasing or decreasing their allocations for 2009."
	.Item("quote_b11_3") = "Major Investment Bank"
	.Item("quote_a12_3") = "There should be some discussion as to how the lending community will be dealing with upcoming CMBS maturities … is there a market forming to replace this debt? If so, at what type of terms?"
	.Item("quote_b12_3") = "Major Investment Bank"
	.Item("quote_a13_3") = "There should be a lot of properties coming on the market in 2009 as some companies will be forced to sell. That’s good news for those who don’t need financing."
	.Item("quote_b13_3") = "Senior Executive, Ownership Side of Life Insurance Company"

	.Item("step_title_1a") = "Step 1 - Choose Report"
	.Item("step_title_1b") = "Step 1 - Choose Report and Product"
	.Item("step_title_2a") = "Step 2 - Choose Property and Market"
	.Item("step_title_ajax") = "Choose Report, Product, Property and Market"

	.Item("display_report") = "Display Report"

	.Item("error_a") = "You have not specified any property for your report.<br>Please go back and choose one property from the drop-down list."
	.Item("error_b") = "It is not possible to specify all properties for this report.<br>Please go back and narrow down your selection by selecting one particular product type and/or one property from the drop-down list."
	.Item("error_c") = "Sorry, you do not have access to this report."
	.Item("error_d") = "There is no data available for the selected Product Type.<br>Please go back and choose a different Product Type from the drop-down list."

	.Item("error_email_notfound") = "Your e-mail address was not found in our records."

	.Item("report_R000") = "Report Title"
	.Item("report_R100") = "Investor Outlook"
	.Item("report_R101") = "Valuation Parameters"
	.Item("report_R102") = "Historical Valuation Parameters"
	.Item("report_R120") = "Tier I Regional Mall Rental Rate Inflation"				' *** NEW
	.Item("report_R121") = "Rental Building Expenses (% EGI)"						' *** NEW
	.Item("report_R122") = "Rental Building Expenses ($ per suite)"					' *** NEW
	.Item("report_R123") = "Office Tenant Retention Ratio"							' *** NEW
	.Item("report_R124") = "Retail Rental Inflation"								' *** NEW
	.Item("report_R125") = "Industrial Net Rental Rates"							' *** NEW
	.Item("report_R126") = "Leasehold Parameters"									' *** NEW
	.Item("report_R127") = "Toronto Office New Construction Valuation Parameters"	' *** NEW
	.Item("report_R128") = "Montreal Midtown Valuation Parameters"					' *** NEW
	.Item("report_R129") = "Montreal Midtown Valuation Parameters Investor Outlook"	' *** NEW
	.Item("report_R130") = "Investor Outlook - New Construction"					' *** NEW
	.Item("report_R131") = "Retail Rental Rate & Expense Inflation"					' *** NEW
	.Item("report_R132") = "Industrial Initial Net Rental Rate"						' *** NEW
	.Item("report_R133") = "Development Yield & Cap Rate"							' *** NEW
	.Item("report_R134") = "Appropriate Third Party Management Fees"				' *** NEW
	.Item("report_R135") = "Office Lag Vacancy"										' *** NEW
	.Item("report_R136") = "Typical Marketing Time"									' *** NEW
	.Item("report_R137") = "Retail Vacancy & Credit Allowance"						' *** NEW
	.Item("report_R138") = "Annual Tenant Turnover"									' *** NEW
	.Item("report_R139") = "Annual Tenant Turnover Cost"							' *** NEW
	.Item("report_R200") = "Market Net Effective Rates"
	.Item("report_R201") = "Market Face Rates"
	.Item("report_R202") = "Economic Face Rates"
	.Item("report_R203") = "Development Yields"
	.Item("report_R300") = "Face Rate Forecast"
	.Item("report_R400") = "Product/Market Barometer"
	.Item("report_R401") = "Location Barometer"
	.Item("report_R402") = "Property Type Barometer"
	.Item("report_R403") = "Rolling Four Quarter Location Barometer"
	.Item("report_R404") = "Rolling Four Quarter Property Type Barometer"
	.Item("report_R500") = "Office Vacancy Barometer"
	.Item("report_R110") = "Leasehold Investor Outlook"
	.Item("report_R111") = "Leasehold Valuation Parameters"
	.Item("report_H100") = "Investor Outlook"
	.Item("report_H101") = "Valuation Parameters"
	.Item("report_H200") = "Market Net Effective Rates"
	.Item("report_H201") = "Market Face Rates"
	.Item("report_H202") = "Economic Face Rates"
	.Item("report_H203") = "Development Yields"
	.Item("report_H400") = "Product/Market Barometer"
	.Item("report_H401") = "Location Barometer"
	.Item("report_H402") = "Property Type Barometer"
	.Item("report_H500") = "Office Vacancy Barometer"
	.Item("report_H110") = "Leasehold Investor Outlook"
	.Item("report_H111") = "Leasehold Valuation Parameters"
	.Item("report_X100") = "Respondent Categories"
	.Item("report_S100") = "Motivation for Office Investment"
	.Item("report_S101") = "Motivation for Retail Investment"
	.Item("report_S102") = "Motivation for Multi Residential Investment"
	.Item("report_S200") = "Threats To Multi Residential Investment"
	.Item("report_S300") = "Availability of New Real Estate Equity"
	.Item("report_S301") = "Expected Price Performance of Real Estate Equities"
	.Item("report_S302") = "Total Required Rate of Return"
	.Item("report_S303") = "Cost of Debt Outlook"
	.Item("report_S304") = "Capital Sources"
	.Item("report_S305") = "Overall Capitalization Rates"
	.Item("report_S306") = "Internal Rates of Return"
	.Item("report_S307") = "Calculation of Reversion Value"						' *** NEW
	.Item("report_S308") = "Interest Rate Impact"								' *** NEW
	.Item("report_S309") = "Discounted Cash Flow"								' *** NEW
	.Item("report_S310") = "Gross Rent to Sales Ratio"							' *** NEW
	.Item("report_S311") = "Third Party Property Management Fees"				' *** NEW
	.Item("report_S312") = "Retail Tenant Retention Ratio"						' *** NEW
	.Item("report_S313") = "Net Effective Discount Period"						' *** NEW
	.Item("report_S314") = "Retail Lag Vacancy"									' *** NEW
	.Item("report_S315") = "Homogeneous Portfolio Effect"						' *** NEW
	.Item("report_T100") = "Conventional Debt Market Parameters"				' *** NEW
	.Item("report_T101") = "Financial Indicators"								' *** NEW
	.Item("report_T102") = "Selling Costs at Reversion"							' *** NEW

	.Item("report_R000_subtitle") = "Report Subtitle"
	.Item("report_R500_subtitle") = "(NEXT THREE MONTHS)"
	.Item("report_S303_subtitle") = "(CONVENTIONAL FIRST MORTGAGE, NEXT THREE MONTHS)"
	.Item("report_S304_subtitle") = "(MOST ACTIVE SOURCES OF FIRST MORTGAGE DEBT CAPITAL)"
	.Item("report_S10X_subtitle") = "(RANKING OF MAJOR MOTIVES)"
	.Item("report_S30X_subtitle") = "(Reits and Corporations - Next Twelve Months)"

	.Item("chart_item_percent") = "PERCENT"
	.Item("chart_item_dollarpersqft") = "$ PER SQUARE FOOT"
	.Item("chart_item_dollarpersuite") = "$ PER SUITE"
	.Item("chart_item_persqft") = "Per Square Foot"
	.Item("chart_item_persqft_short") = "PSF"
	.Item("chart_item_persuite") = "Per Suite"
	.Item("chart_item_persuite_short") = "PS"
	.Item("chart_item_historical") = "Historical"
	.Item("chart_item_rolling4qtrs") = "Rolling Four Quarters"
	.Item("chart_item_nrofrespondents") = "No. of Respondents"
	.Item("chart_item_respondents") = "Respondents"
	.Item("chart_item_max") = "Max"
	.Item("chart_item_min") = "Min"
	.Item("chart_item_avg") = "Avg"
	.Item("chart_item_change") = "Change"
	.Item("chart_item_dollar") = "$"
	.Item("chart_item_current") = "Current"
	.Item("chart_item_qtr_rolling4") = "Rolling Four Quarters"
	.Item("chart_item_qtr_current") = "Current Quarter"
	.Item("chart_item_top15least15") = "(Top 15 Preferred/15 Least Preferred)"
	.Item("chart_item_minmaxarea") = "(MIN - MAX AREA)"
	.Item("chart_item_minmaxrange") = "(MIN - MAX RANGE)"
	.Item("chart_item_average") = "(AVERAGE)"
	.Item("chart_item_count") = "(COUNT)"
	.Item("chart_item_months") = "MONTHS"
	.Item("chart_item_pctgrossincome") = "PERCENTAGE OF EFFECTIVE GROSS INCOME"
	.Item("chart_item_monthly") = "MONTHLY"
	.Item("chart_item_annually") = "ANNUALLY"
	.Item("chart_item_dontknow") = "DON'T KNOW"

	.Item("chart_item_head_a1") = "Overall Cap. Rate"
	.Item("chart_item_head_a2") = "Internal Rate of Return"
	.Item("chart_item_head_a3") = "Terminal Cap. Range"
	.Item("chart_item_head_b1") = "Momentum Ratio"
	.Item("chart_item_head_c1") = "Next 12 Months"
	.Item("chart_item_head_c2") = "13-24 Months"
	.Item("chart_item_head_c3") = "25-36 Months"
	.Item("chart_item_head_c4") = "Beyond 36 Months"
	.Item("chart_item_head_d1") = "NUMBER OF RESPONDENTS"
	.Item("chart_item_head_d2") = "% OF RESPONDENTS"
	.Item("chart_item_head_d3") = "Percentage of Respondents"
	.Item("chart_item_head_e1") = "Increase"
	.Item("chart_item_head_e2") = "Decrease"
	.Item("chart_item_head_e3") = "No Change"
	.Item("chart_item_head_f1") = "Overall Capitalization Rate"
	.Item("chart_item_head_f2") = "Internal Rate of Return"
	.Item("chart_item_head_f3") = "Terminal Capitalization Rate"
	.Item("chart_item_head_f4") = "$ PSF"

	.Item("chart_item_unit_a1") = "N/A"
	.Item("chart_item_unit_a2") = "TREND"
	.Item("chart_item_unit_a3") = "SQ.FT"
	.Item("chart_item_unit_a4") = "PERCENT"
	.Item("chart_item_unit_a5") = "MOMENTUM RATIO (BUY % / SELL %)"
	.Item("chart_item_unit_a6") = "$ PER BUILDABLE SQUARE FOOT"
	.Item("chart_item_unit_a7") = "NUMBER OF RESPONDENTS"
	.Item("chart_item_unit_a8") = "PERCENTAGE OF RESPONDENTS"
	.Item("chart_item_unit_a9") = "$ PER SQUARE FOOT"
	.Item("chart_item_unit_a10") = "MOMENTUM RATIO (Positive Indicates Vacancy Decreasing)"

	.Item("chart_item_desc_a1") = "N/A"
	.Item("chart_item_desc_a2") = "TREND"
	.Item("chart_item_desc_a3") = "SQ.FT"
	.Item("chart_item_desc_b1") = "OVERALL CAPITALIZATION RATE RANGE"
	.Item("chart_item_desc_b2") = "INTERNAL RATE OF RETURN RANGE"
	.Item("chart_item_desc_b3") = "TERMINAL CAPITALIZATION RATE RANGE"
	.Item("chart_item_desc_b4") = "INTERNAL RATE OF RETURN RANGE (LEVERED)"
	.Item("chart_item_desc_c1") = "NEXT 12 MONTHS"
	.Item("chart_item_desc_c2") = "13-24 MONTHS"
	.Item("chart_item_desc_c3") = "25-36 MONTHS"
	.Item("chart_item_desc_c4") = "BEYOND 36 MONTHS"
	.Item("chart_item_desc_e1") = "INCREASE"
	.Item("chart_item_desc_e2") = "DECREASE"
	.Item("chart_item_desc_e3") = "NO CHANGE"
	.Item("chart_item_desc_f1") = "OVERALL CAPITALIZATION RATE"
	.Item("chart_item_desc_f2") = "INTERNAL RATE OF RETURN"
	.Item("chart_item_desc_f3") = "TERMINAL CAPITALIZATION RATE"
	.Item("chart_item_desc_f4") = "$ PER SQUARE FOOT"

	.Item("chart_item_scale_a1") = "INITIAL|RETURN"
	.Item("chart_item_scale_a2") = "CASH FLOW|UPSIDE (GROWTH)"
	.Item("chart_item_scale_a3") = "CAPITAL|APPRECIATION"
	.Item("chart_item_scale_a4") = "REQUIREMENT TO|PLACE CAPITAL"
	.Item("chart_item_scale_a5") = "POOR PERFORMANCE OF|ALTERNATIVE INVESTMENTS"
	.Item("chart_item_scale_a6") = "AVAILABILITY AND LOW|COST OF DEBT/EQUITY"
	.Item("chart_item_scale_a7") = "ENHANCES / UPGRADES|EXISTING PORTFOLIO"
	.Item("chart_item_scale_a8") = "OPERATING MANAGEMENT|/ EFFICIENCIES"
	.Item("chart_item_scale_a9") = "FLIGHT|CAPITAL"

	.Item("chart_item_scale_b1") = "DEBT|COSTS"
	.Item("chart_item_scale_b2") = "POTENTIAL LOAN|(DEBT) TO VALUE"
	.Item("chart_item_scale_b3") = "STABILITY OF VALUE|VERSUS OTHER ASSET TYPES"
	.Item("chart_item_scale_b4") = "CAPITAL|GROWTH"
	.Item("chart_item_scale_b5") = "STABILITY|OF INCOME"
	.Item("chart_item_scale_b6") = "INCOME|GROWTH"
	.Item("chart_item_scale_b7") = "HIGH COST OF|NEW CONSTRUCTION"
	.Item("chart_item_scale_b8") = "CMHC|INSURANCE"

	.Item("chart_item_scale_c1") = "UNEXPECTED|CAPITAL COSTS"
	.Item("chart_item_scale_c2") = "LEGISLATIVE CHANGES|(RENT CONTROL)"
	.Item("chart_item_scale_c3") = "DEBT|COSTS"
	.Item("chart_item_scale_c4") = "ENERGY|COSTS"
	.Item("chart_item_scale_c5") = "REALTY|TAXES"
	.Item("chart_item_scale_c6") = "ECONOMIC|CONDITIONS"
	.Item("chart_item_scale_c7") = "CMHC|INSURANCE"
	.Item("chart_item_scale_c8") = "VACANCY /|AVAILABILITY"

	.Item("chart_item_scale_d1") = "LARGE CAP REIT"
	.Item("chart_item_scale_d2") = "SMALL CAP REIT"
	.Item("chart_item_scale_d3") = "SMALL CAP CORPORATION"

	.Item("chart_item_scale_e1") = "REITs"
	.Item("chart_item_scale_e2") = "Corporations"

	.Item("chart_item_scale_f1") = "DOWNTOWN CLASS 'AA' OFFICE"
	.Item("chart_item_scale_f2") = "TIER I REGIONAL MALL"
	.Item("chart_item_scale_f3") = "MULTI-TENANT INDUSTRIAL"
	.Item("chart_item_scale_f4") = "MULTIPLE UNIT RESIDENTIAL"

	.Item("dir_up") = "UP"
	.Item("dir_down") = "DOWN"
	.Item("dir_same") = "SAME"

	.Item("list_of_graphs_for") = "List of Available Graphs for"
	.Item("hist_qtr_snapshot") = "Select Historical Quarter Snapshot"

	.Item("chart_legend_a") = "Arrows indicate directional movement from previous survey"
	.Item("chart_legend_b") = "(TOTALS - NEXT 12 MONTHS)"

	.Item("historical") = "HISTORICAL QUARTER SNAPSHOT"
	.Item("historical_snap") = "HISTORICAL SNAPSHOTS"
	.Item("history_all") = "ALL AVAILABLE HISTORY"
	.Item("history_top5") = "MOST RECENT 5 QUARTERS"

	.Item("qtr_frequency") = "QUARTERLY FREQUENCY"
	.Item("topics") = "TOPICS"

	' New after January 2009

	.Item("bps") = "bps"
	.Item("avg_dollar_ps") = "Average $PS"

	.Item("chart_item_scale_g1") = "MARKET RENT INFLATION"
	.Item("chart_item_scale_g2") = "GROSS SALES INFLATION YEAR 1"
	.Item("chart_item_scale_g3") = "GROSS SALES INFLATION YEARS 2-5"
	.Item("chart_item_scale_g4") = "GROSS SALES INFLATION YEARS 6-10"
	.Item("chart_item_scale_g5") = "EXPENSES INFLATION"

	.Item("chart_item_scale_h1") = "MANAGEMENT"
	.Item("chart_item_scale_h2") = "RESERVE ALLOWANCE - CAPITAL ITEMS"
	.Item("chart_item_scale_h3") = "REPAIRS & MAINTENANCE"
	.Item("chart_item_scale_h4") = "STAFFING"
	.Item("chart_item_scale_h5") = "SECURITY"
	.Item("chart_item_scale_h6") = "ADVERTISING"

	.Item("chart_item_scale_i1") = "RENTAL INFLATION"
	.Item("chart_item_scale_i2") = "EXPENSE INFLATION"

	.Item("chart_item_scale_j1") = "YEARS 1-5"
	.Item("chart_item_scale_j2") = "YEARS 6-10"

	.Item("chart_max_loan_to_value") = "Maximum Loan to Value"
	.Item("chart_min_spread") = "Minimum Spread"

	.Item("chart_max_loan_to_value_ratio") = "Maximum Loan to Value Ratio"
	.Item("chart_min_spread_10yr") = "Minimum Spread Over 10 Yr Canada Bonds"
	.Item("chart_longest_amortization") = "Longest Amortization"
	.Item("chart_current_availability") = "Current Availability (%)"
	.Item("chart_minimum_debt") = "Minimum Debt Service Ratio (%)"
	.Item("chart_min_spread_5yr") = "Minimum Spread Over 5 Yr Canada Bonds"
	.Item("chart_preferred_term") = "Prefered Term Today (yrs)"
	.Item("chart_additional_bps") = "Additional BPS Cost to Preferred Term"

	.Item("chart_rent_inflation") = "Rent Inflation"
	.Item("chart_expense_inflation") = "Expense Inflation"

	.Item("chart_initial_net_rental_rate") = "Initial Net Rental Rate"

	.Item("chart_development_yield") = "Development Field"
	.Item("chart_stabilized_cap_rate") = "Stabilized Cap Rate"
	.Item("chart_asset_value") = "Asset Value ($000,000s)"

	.Item("L_LEVEL_1") = "Less than 2.0%"
	.Item("L_LEVEL_2") = "2.01% to 2.50%"
	.Item("L_LEVEL_3") = "2.51% to 3.0%"
	.Item("L_LEVEL_4") = "3.01% to 3.50%"
	.Item("L_LEVEL_5") = "More than 3.50%"

	.Item("L_CAPITALIZE_BEFORE") = "Capitalize NOI - Before structural allowance"
	.Item("L_CAPITALIZE_AFTER") = "Capitalize NOI - After structural allowance"
	.Item("L_CAPITALIZE_CASHFLOW") = "Capitalize Cash Flow"

	.Item("L_1ST") = "1st"
	.Item("L_2ND") = "2nd"
	.Item("L_3RD") = "3rd"
	.Item("L_4TH") = "4th"
	.Item("L_5TH") = "5th"
	.Item("L_6TH") = "6th"

	.Item("chart_dcfirr") = "DCF / IRR"
	.Item("chart_noi_yield_year") = "NOI YIELD YEAR 1"
	.Item("chart_noi_yield_avg") = "NOI YIELD - AVERAGE YEARS 1-5"
	.Item("chart_cf_yield_year") = "CF YIELD YEAR 1"
	.Item("chart_cf_yield_avg") = "CF YIELD - AVERAGE YEARS 1-5"

	.Item("L_000") = "0.00%"
	.Item("L_005") = "0.05%"
	.Item("L_025") = "0.25%"
	.Item("L_040") = "0.40%"
	.Item("L_050") = "0.50%"
	.Item("L_060") = "0.60%"
	.Item("L_070") = "0.70%"
	.Item("L_075") = "0.75%"
	.Item("L_080") = "0.80%"
	.Item("L_085") = "0.85%"
	.Item("L_100") = "1.00%"
	.Item("L_110") = "1.10%"
	.Item("L_113") = "1.13%"
	.Item("L_120") = "1.20%"
	.Item("L_125") = "1.25%"
	.Item("L_130") = "1.30%"
	.Item("L_133") = "1.33%"
	.Item("L_150") = "1.50%"
	.Item("L_165") = "1.65%"
	.Item("L_175") = "1.75%"
	.Item("L_199") = "1.99%"
	.Item("L_200") = "2.00%"
	.Item("L_225") = "2.25%"
	.Item("L_250") = "2.50%"
	.Item("L_275") = "2.75%"
	.Item("L_300") = "3.00%"
	.Item("L_325") = "3.25%"
	.Item("L_350") = "3.50%"
	.Item("L_400") = "4.00%"
	.Item("L_450") = "4.50%"
	.Item("L_500") = "5.00%"

	.Item("L_5_10") = "5-10"
	.Item("L_10_20") = "10-20"
	.Item("L_20_50") = "20-50"
	.Item("L_50_100") = "50-100"
	.Item("L_100_PLUS") = "100+"

	.Item("L_10_11_PCT") = "10.00% to 11.00%"
	.Item("L_11_12_PCT") = "11.01% to 12.00%"
	.Item("L_12_13_PCT") = "12.01% to 13.00%"
	.Item("L_13_14_PCT") = "13.01% to 14.00%"
	.Item("L_14_15_PCT") = "14.01% to 15.00%"
	.Item("L_15_16_PCT") = "15.01% to 16.00%"
	.Item("L_16_17_PCT") = "16.01% to 17.00%"
	.Item("L_17_18_PCT") = "17.01% to 18.00%"

End With

%>
